### ISSUE TITLE
NOT FUCTIONING

### ISSUE THREAD

**Issue by bonvayage** [marcoslafoz/VintedBot#1]
Hello

the bot does not work

**Comment by marcoslafoz** [comment]
I'll try to fix it

**Comment by bonvayage** [comment]
let me know if the bot start to work again

**Comment by pedroatletico** [comment]
buenas esta funcionando?si es asi como contacto contigo porque necesito ayuda

**Comment by marcoslafoz** [comment]
@pedroatletico No, no esta funcionando

**Comment by pedroatletico** [comment]
sabes de alguno que funcione?es que he probado muchos y no me sirve ninguno sobre todo en python gracias
